spring:
  r2dbc:
    password: '12345'
    url: r2dbc:h2:file:///./testdb
    username: sa
  application:
    name: 'ms-sofftek-interview-leonardo-ballestero-v1'
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
info:
  project:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    type: microservice
    artifact-id: '@project.artifactId@'
    app-group: INTERVIEW
